const worlds=document.querySelectorAll(".world");const title=document.querySelector("#mission-title");const intro=document.querySelector("#mission-intro");const showAll=document.querySelector("#show-all");const names={explorer:"Explorer",musician:"Musician",producer:"Producer",designer:"Designer",media:"Media Maker",coder:"Coder"};
const grid=document.querySelector(".grid");
(window.quickMissions||[]).forEach(m=>{const a=document.createElement("article");a.className="card quick-card";a.dataset.track=m.track;a.innerHTML=`<div class="tag">${m.trackLabel} · QUICK</div><h3>${m.title}</h3><p>${m.mission}</p><div class="bottom"><span>${m.duration}</span><button class="mission-open" data-id="${m.id}">Start quick →</button></div>`;grid.appendChild(a);});
function cards(){return document.querySelectorAll(".card")}
function filterMissions(filter){cards().forEach(card=>card.classList.toggle("hidden",filter!=="all"&&card.dataset.track!==filter));if(filter==="all"){title.textContent="Alle missies";intro.textContent="Kies een QUICK voor een korte start of een langere missie als je meer tijd hebt.";showAll.classList.add("hidden");}else{title.textContent=names[filter]+" missies";intro.textContent="Kies een korte QUICK of ga voor een langere missie.";showAll.classList.remove("hidden");}document.querySelector("#missies").scrollIntoView({behavior:"smooth",block:"start"});}
worlds.forEach(world=>world.addEventListener("click",()=>filterMissions(world.dataset.filter)));showAll.addEventListener("click",()=>{filterMissions("all");document.querySelector("#werelden").scrollIntoView({behavior:"smooth"});});
function showQuick(id){const m=(window.quickMissions||[]).find(x=>x.id===id);if(!m)return;const old=document.querySelector("#quick-modal");if(old)old.remove();const modal=document.createElement("div");modal.id="quick-modal";modal.className="quick-overlay";modal.innerHTML=`<section class="quick-sheet" role="dialog" aria-modal="true" aria-label="${m.title}"><button class="quick-close" aria-label="Sluiten">×</button><p class="kicker">${m.trackLabel} · QUICK · ${m.duration}</p><h2>${m.title}</h2><div class="quick-mission"><strong>MISSIE</strong><p>${m.mission}</p></div><h3>DOE</h3><ol class="quick-steps">${m.steps.map(s=>`<li>${s}</li>`).join("")}</ol><div class="quick-two"><div class="quick-done"><strong>✓ KLAAR?</strong><p>${m.done}</p></div><div class="quick-extra"><strong>★ EXTRA</strong><p>${m.extra}</p></div></div><div class="quick-tools"><strong>NODIG</strong> · ${m.tools}</div></section>`;document.body.appendChild(modal);modal.querySelector(".quick-close").focus();modal.querySelector(".quick-close").onclick=()=>modal.remove();modal.onclick=e=>{if(e.target===modal)modal.remove()};}
document.addEventListener("click",e=>{const b=e.target.closest(".mission-open");if(b)showQuick(b.dataset.id)});
document.addEventListener("keydown",e=>{if(e.key==="Escape"){const m=document.querySelector("#quick-modal");if(m)m.remove();}});
const existing=[...document.querySelectorAll(".card:not(.quick-card) a")].map(a=>({kind:"url",value:a.href}));const quick=(window.quickMissions||[]).map(m=>({kind:"quick",value:m.id}));const all=[...existing,...quick];document.querySelector("#surprise").addEventListener("click",()=>{const c=all[Math.floor(Math.random()*all.length)];if(c.kind==="url")window.location.href=c.value;else showQuick(c.value);});
